name: CI

on:
  push:
    branches:
      - main # main 브랜치에 push될 때 트리거
      - develop # main 브랜치에 push될 때 트리거

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:23.0.5
        options: --privileged # Docker-in-Docker 지원

    env:
      DOCKER_IMAGE: junwoo5914/nca2025

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: SignIn to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build Docker images
        run: docker compose build

      - name: Tag and push Docker images
        run: |
          docker tag course-client:latest "${{ env.DOCKER_IMAGE }}:client-${{ github.ref_name }}"
          docker push "${{ env.DOCKER_IMAGE }}:client-${{ github.ref_name }}"
